# any constants that are useful in any config must be included here
static_columns:
  # the index of the split column(values: "train", "test" or "valid")
  FINAL_SPLIT_INDEX: 0

  # in classification: index of the label-index-column
  # in regression: label value is placed in column FINAL_LABEL_INDEX
  FINAL_LABEL_INDEX: 1

  # in classification: index of the label value column
  # in regression: dummy column, not needed as FINAL_LABEL_INDEX holds all
  #                needed  information
  FINAL_LABEL_NAME_INDEX: 2






