###############################################################################
###############################################################################
###################### PLEASE DON'T MODIFY THIS EXAMPLE #######################
###############################################################################
###############################################################################
# Copy to configs file and rename somehow

includes:
  - configs/constant_configs.yml


dataset:
  input_path: processed_data/pima-indians-diabetes.data
  label_type: classification

model:
  # name can be a registered model, all registered models are in modules/models/
  # name can be a path to the class of outside library
  # for example:
  # name: sklearn.linear_model.LogisticRegression
  name: sklearn.linear_model.LogisticRegression
  # tag must be a unique value among other tags, this way we distinguish
  # models during the prediction step
  tag: uan2


# This inputs will be used as parameters for the model
special_inputs:
  tol: 0.0001
  C: 1


trainer:
  # Possible trainers:
  # 1. torch_trainer - for all torch related models
  # 2. sklearn_trainer - for all sklearn related models
  name: sklearn_trainer
  # optim is not needed when trainer is sklearn_trainer
  # optim can be a torch optimizer, any optim from torch.optim
  optim: Adam
  # loss can be any loss from torch.nn
  # Examples: NLLLoss, MSELoss, example_loss, <your custom loss defined in modules/losses>
  loss: NLLLoss
  # set it to 0, null or false to not save, otherwise - saves
  save: 1
  epochs: 10
  # log valid, train loss and metrics every log_valid_every epochs
  log_valid_every: 2
  # hps that go to ray tune.run function
  tune:
    resources_per_trial:
      cpu: 2
      gpu: 0
  # name of checkpoint_metric is used to choose the best model
  # "checkpoint_metric" is chosen based on valid set metrics
  # Possible names examples: valid_precision, valid_mse, valid_<loss>
  checkpoint_metric:
    name: valid_accuracy
    mode: max  # choose max or min


# must be same hps actual optimizer
# names must be the same as the actual parameters of the optimizer
optim:
  lr: 0.01
  weight_decay: 0.00001


# list of registered metrics that are used during training on valid
metrics:
    - accuracy  # classification only
    - precision  # classification only
#  - mse  # regression and classification

# comment out features that you don't want to train on
features_list:
  - 2-Hour
  - Body mass
  - Triceps_1
  - Triceps_10
  - Triceps_11
  - Triceps_12
  - Triceps_13
  - Triceps_14
  - Triceps_15
  - Triceps_16
  - Triceps_17
  - Triceps_18
  - Triceps_19
#  - Triceps_2
#  - Triceps_20
#  - Triceps_21
#  - Triceps_22
#  - Triceps_23
#  - Triceps_24
  - Triceps_25
  - Triceps_26
  - Triceps_27
  - Triceps_28
  - Triceps_29
  - Triceps_3
  - Triceps_30
  - Triceps_31
  - Triceps_32
  - Triceps_33
  - Triceps_34
  - Triceps_35
  - Triceps_36
  - Triceps_37
  - Triceps_38
  - Triceps_39
  - Triceps_4
  - Triceps_40
  - Triceps_41
  - Triceps_42
  - Triceps_43
  - Triceps_44
  - Triceps_45
  - Triceps_46
  - Triceps_47
  - Triceps_48
  - Triceps_49
  - Triceps_5
  - Triceps_50
  - Triceps_51
  - Triceps_6
  - Triceps_7
  - Triceps_8
  - Triceps_9
