dataset:
  name: basket_dataset

  data_loaders:

    train:
      batch_size: 128
      shuffle: true
      num_workers: 4
      multiprocessing_context: spawn
      pin_memory: true

    valid:
      batch_size: 64
      shuffle: false
      num_workers: 4
      multiprocessing_context: spawn
      pin_memory: true

    test:
      batch_size: 64
      shuffle: false
      num_workers: 4
      multiprocessing_context: spawn
      pin_memory: true


# this inputs will go to your specific model __init__
special_inputs:
  transformers: [goals_ohe, adj]
  CE_weight: 0.01
  adjacency_type: 1
  alpha: 0.2
  clip: 10
  g_dim: 90
  graph_hid: 8
  graph_model: gcn
  h_dim: 64
  n_heads: 4
  n_layers: 2
  obs_len: 10
  players: atk
  pred_len: 40
  print_every_batch: 30
  rnn_dim: 64
  save_every: 10
  seed: 128
  sigma: 1.2
  top_k_neigh: null
  warmup: false
  x_dim: 2
  z_dim: 32
  mode: raw
  wrmp_epochs: 50
  _lambda: 0.01









