includes:
  - configs/constant_configs.yml


k_fold: 2
preprocessing: preprocessing_regression
train: [train_xgboost_regression]
prediction: prediction_regression


models:
#  uan: dense_net_regression
  uan3: xgb_regressor
#  uan4: linear_regression

metrics: [mse, accuracy]