includes:
  - configs/constant_configs.yml

predictor: player_evaluation

dataset:
  input_path: processed_data/merged_df_v62


models:
  uan: dense_net_regression
  uan3: xgb_regressor
  uan4: linear_regression


metrics: [mse]