includes:
  - configs/constant_configs.yml

predictor: player_valuation_predictor

dataset:
  input_path: processed_data/player_valuation2_no_first_year


print_important_features: true


splits:
  - train
  - valid
  - test

plots:
  steps_func:
    - get_abs_diff
    - get_abs_mean_fraction_true_minus_pred_over_true
    - get_mean_fraction_true_minus_pred_over_true
    - get_rmse
    - get_mean_fraction_larger_over_smaller


models:
  no_first_year: xgb_regressor
  no_first_year: linear_regression


metrics: [mse, r2]