includes:
  - configs/constant_configs.yml

predictor: pandas_predictor

dataset:
  input_path: processed_data/iris


models:
  uan: dense_net
#  uan2: random_forest_classifier
#  uan3: logistic_regression


metrics: [mse]