includes:
  - configs/constant_configs.yml

dataset:
  input_path: processed_data/toy_dataset_output.csv
  type: csv


models:
  uan: dynamic_net
  uan2: rfc

  
trainer:
    name: torch_trainer
    save: 1
    epochs: 100
    log_valid_every: 20


dataset:
  input_path: processed_data/toy_dataset_output.csv
  type: csv


