includes:
  - configs/constant_configs.yml

predictor: player_evaluation_predictor

classification: false

dataset:
  input_path: processed_data/no_GK_merged_df_v62

trainer:
  name: sklearn_trainer

print_important_features: true

plots:
  splits:
    - train
    - valid
    - test
  steps_func:
    - get_abs_diff
    - get_abs_mean_fraction
    - get_mean_fraction
    - get_rmse


models:
#  uan: dense_net_regression
#  uan3: xgb_regressor
  small: xgb_regressor
#  uan4: linear_regression


metrics: [mse]