includes:
  - configs/constant_configs.yml
  - configs/dagnet_constant_configs.yml

predictor: multi_regression_predictor

dataset:
  input_path: processed_data/dagnet_dataset

print_important_features: false


plots:
  splits:
    - train
    - valid
    - test
  steps_func:
    - get_abs_diff
    - get_abs_mean_fraction
    - get_mean_fraction
    - get_rmse


models:
  uan: dagnet
#  uan: linear_regression


metrics: [dagnet_loss]