includes:
  - configs/constant_configs.yml

dataset:
  input_path: processed_data/toy_dataset_output.csv
  type: csv


models:
  uan: dense_net
  uan2: rfc

  
trainer:
    name: torch_trainer
    tag: 'uan'
    resources_per_trial:
      cpu: 2
      gpu: 0
    save: 1
    epochs: 100
    log_valid_every: 20


dataset:
  input_path: processed_data/toy_dataset_output.csv
  type: csv


