includes:
  - configs/constant_configs.yml

dataset:
  input_path: processed_data/merged_df_v42


models:
  uan: dense_net_regression
  uan2: lasso
  uan3: xgb_regressor
  uan4: linear_regression


metrics: [mse]