includes:
  - configs/constant_configs.yml

predictor: player_valuation_predictor

dataset:
  input_path: processed_data/player_valuation2


print_important_features: true


splits:
#  - train
#  - valid
  - test

plots:
  steps_func:
#    - get_abs_diff
#    - get_abs_mean_fraction_true_minus_pred_over_true
    - get_mean_fraction_true_minus_pred_over_true
#    - get_rmse
    - get_mean_fraction_larger_over_smaller


models:
  with_first_year_xgb: xgb_regressor
  with_first_year_lr: linear_regression
  with_first_year_net: dense_net_regression


metrics: [mse, r2]