includes:
  - configs/constant_configs.yml

predictor: player_evaluation_predictor

classification: false

dataset:
  input_path: processed_data/no_GK_merged_df_v62


print_important_features: true


splits:
#  - train
#  - valid
  - test

plots:
  steps_func:
    - get_abs_diff
    - get_abs_mean_fraction
    - get_mean_fraction
    - get_rmse


models:
  uan: dense_net_regression
#  uan3: xgb_regressor
  small: xgb_regressor
#  uan4: linear_regression
#  uan3k_fold1: xgb_regressor
#  uan3k_fold0: xgb_regressor


metrics: [mse]