includes:
  - configs/constant_configs.yml

predictor: player_valuation_predictor

dataset:
  input_path: processed_data/player_valuation2


print_important_features: true


splits:
  - train
  - valid
  - test

plots:
  steps_func:
#    - get_abs_diff
    - get_abs_mean_fraction_true_minus_pred_over_true
    - get_mean_fraction_true_minus_pred_over_true
#    - get_rmse
    - get_mean_fraction_larger_over_smaller


models:
#  with_first_year_rf: random_forest_regressor
#  with_first_year: xgb_regressor
  no_first_year: xgb_regressor
#  uan4: random_forest_regressor


metrics: [mse, r2]