includes:
  - configs/constant_configs.yml


reader:
  name: xlsx_reader
  sheet_name: Sheet1
  label_type: regression  # classification or regression
  input_path: data/no_GK_merged_df_v62
  limit: null
  # index or name of the labels column in the input data
  label: value
  shuffle: 1 # can be (0, false null) OR (anything else, which means true)
   # if "split_ratio" doesn't sum to 1, then valid + test will be 1 - train
  split_ratio:
    train: 0.8
    valid: 0.1
    test: 0.1

to_all_features: []


#Pick Transformers(defined in modules/transformers/) or create your own
#defined: norm, ohe
features_list:
  Team_encoded: []
  nationality_encoded: []
  name: []
  id: []
  Team: [ohe]
  a_w: [ohe]
  bp: [ohe]
  d_w: [ohe]
  foot: [ohe]
  nationality: [ohe]
  total_stats: [min_max_scaler]
  base_stats: [min_max_scaler]
  age: [square, min_max_scaler]
  ova: [min_max_scaler]
  pot: [min_max_scaler]
  foot.1: [min_max_scaler]
  bov: [min_max_scaler]
  growth: [min_max_scaler]
  joined: [min_max_scaler]
  wage: [min_max_scaler]
  release_clause: [min_max_scaler]
  attacking: [min_max_scaler]
  crossing: [min_max_scaler]
  finishing: [min_max_scaler]
  heading_accuracy: [min_max_scaler]
  short_passing: [min_max_scaler]
  volleys: [min_max_scaler]
  skill: [min_max_scaler]
  dribbling: [min_max_scaler]
  curve: [min_max_scaler]
  fk_accuracy: [min_max_scaler]
  long_passing: [min_max_scaler]
  ball_control: [min_max_scaler]
  movement: [min_max_scaler]
  acceleration: [min_max_scaler]
  sprint_speed: [min_max_scaler]
  agility: [min_max_scaler]
  reactions: [min_max_scaler]
  balance: [min_max_scaler]
  power: [min_max_scaler]
  shot_power: [min_max_scaler]
  jumping: [min_max_scaler]
  stamina: [min_max_scaler]
  strength: [min_max_scaler]
  long_shots: [min_max_scaler]
  mentality: [min_max_scaler]
  aggression: [min_max_scaler]
  interceptions: [min_max_scaler]
  positioning: [min_max_scaler]
  vision: [min_max_scaler]
  penalties: [min_max_scaler]
  defending: [min_max_scaler]
  marking: [min_max_scaler]
  standing_tackle: [min_max_scaler]
  sliding_tackle: [min_max_scaler]
  goalkeeping: [min_max_scaler]
  gk_diving: [min_max_scaler]
  gk_handling: [min_max_scaler]
  gk_kicking: [min_max_scaler]
  gk_positioning: [min_max_scaler]
  gk_reflexes: [min_max_scaler]
  w_f: [min_max_scaler]
  sm: [min_max_scaler]
  ir: [min_max_scaler]
  pac: [min_max_scaler]
  sho: [min_max_scaler]
  pas: [min_max_scaler]
  dri: [min_max_scaler]
  defe: [min_max_scaler]
  phy: [min_max_scaler]
  On Loan: [min_max_scaler]
  Loan_start_year: [min_max_scaler]
  Loan_end_year: [min_max_scaler]






