includes:
  - configs/constant_configs.yml


reader:
  name: csv_reader
#  sheet_name:
  label_type: regression  # classification or regression
  input_path: data/tf_ws_merged_11012022_dups_removed2
  limit: null
  # index or name of the labels column in the input data
  label: _mv
  shuffle: 1 # can be (0, false null) OR (anything else, which means true)
   # if "split_ratio" doesn't sum to 1, then valid + test will be 1 - train
  split_ratio:
    train: 0.8
    valid: 0.1
    test: 0.1

to_all_features: []


#Pick Transformers(defined in modules/transformers/) or create your own
#defined: norm, ohe
features_list:
  playerid: []
  player_name: []
  joined: [ohe]
  position: [mlb]
  season_start: [min_max_scaler]
  season_end: [min_max_scaler]
  appearance: [min_max_scaler]
  minutes: [min_max_scaler]
  Total_Aerial: [min_max_scaler]
  Won_Aerial: [min_max_scaler]
  Lost_Aerial: [min_max_scaler]
  rating: [min_max_scaler]
  Cross_Assists: [min_max_scaler]
  Corner_Assists: [min_max_scaler]
  Throughball_Assists: [min_max_scaler]
  Freekick_Assists: [min_max_scaler]
  Throwin_Assists: [min_max_scaler]
  Other_Assists: [min_max_scaler]
  Total_Assists: [min_max_scaler]
  ShotsBlocked_Blocks: [min_max_scaler]
  CrossesBlocked_Blocks: [min_max_scaler]
  PassesBlocked_Blocks: [min_max_scaler]
  Yellow_Cards: [min_max_scaler]
  Red_Cards: [min_max_scaler]
  Total_Clearances: [min_max_scaler]
  Unsuccessful_Dribbles: [min_max_scaler]
  Successful_Dribbles: [min_max_scaler]
  TotalDribbles_Dribbles: [min_max_scaler]
  Fouled_Fouls: [min_max_scaler]
  Fouls_Fouls: [min_max_scaler]
  Total_Goals: [min_max_scaler]
  SixYardBox_Goals: [min_max_scaler]
  PenaltyArea_Goals: [min_max_scaler]
  OutOfBox_Goals: [min_max_scaler]
  Total_Interception: [min_max_scaler]
  Total_Keypasses: [min_max_scaler]
  Long_Keypasses: [min_max_scaler]
  Short_Keypasses: [min_max_scaler]
  CaughtOffside_Offsides: [min_max_scaler]
  Total_Passes: [min_max_scaler]
  AccLB_Passes: [min_max_scaler]
  InAccLB_Passes: [min_max_scaler]
  AccSP_Passes: [min_max_scaler]
  InAccSP_Passes: [min_max_scaler]
  UnsuccessfulTouches_Possessionloss: [min_max_scaler]
  Dispossessed_Possessionloss: [min_max_scaler]
  Total_Shots: [min_max_scaler]
  OutOfBox_Shots: [min_max_scaler]
  SixYardBox_Shots: [min_max_scaler]
  PenaltyArea_Shots: [min_max_scaler]
  TotalTackles_Tackles: [min_max_scaler]
  DribbledPast_Tackles: [min_max_scaler]
  TotalAttemptedTackles_Tackles: [min_max_scaler]







