dataset:
  name: csv_dataset
  output_type: csv
  input_path:
    train: data/toy_dataset.csv
    test: data/toy_dataset2.csv
#  input_path: data/toy_dataset.csv
  output_path: processed_data/toy_dataset_output.csv
  label: target
  shuffle: 1
  split_ratio:
    train: 0.8
    valid: 0.1
    test: 0.1
