includes:
  - configs/constant_configs.yml
  - configs/dagnet_constant_configs.yml


model:
  name: dagnet
  tag: uan


# must be same names as parameters of the actual optimizer
optim:
  lr: 0.01
  weight_decay: 0.00001


trainer:
  name: torch_trainer3
  optim: Adam
  loss: dagnet_loss
  save: 1
  epochs: 3
  log_valid_every: 1

  tune:
    resources_per_trial:
      cpu: 2
      gpu: 0

  grid_metric:
    name: valid_avg_kld_loss
    mode: min




#features_list:










