includes:
  - configs/constant_configs.yml


dataset:
  input_path: processed_data/player_valuation2
  label_type: regression


model:
  name: xgboost.XGBRegressor
  tag: uan3

# inputs go to __init__ of the model (sklearn xgboost model in this case)
special_inputs:
  n_estimators: 100
  max_depth: 4
  gamma: .03
  num_parallel_tree:  16
  learning_rate: 0.5
  subsample: .9
  colsample_bytree: 0.8

#special_inputs:
#  n_estimators: [150, 200, 300]
#  max_depth: 2
#  gamma: .03
#  num_parallel_tree:  8
#  learning_rate: [0.5, 0.1, 0.6, 0.3]
#  subsample: [.9, 0.8, 1., 0.7]
#  colsample_bytree: [0.8, 0.7, 0.9, 1.]

trainer:
  name: sklearn_trainer
  save: 1
  tune:
    resources_per_trial:
      cpu: 5
      gpu: 0
    max_concurrent_trials: 54

  checkpoint_metric:
    name: valid_mse
    mode: min

metrics: [mse, r2]


features_list:
#  - club_id
#  - playerid
#  - _mv_millions
  - current_age
  - AccLB_Passes
  - AccSP_Passes
  - Apps_Aerial
  - Apps_Assists
  - Apps_Blocks
  - Apps_Cards
  - Apps_Clearances
  - Apps_Dribbles
  - Apps_Fouls
  - Apps_Goals
  - Apps_Interception
  - Apps_Keypasses
  - Apps_Offsides
  - Apps_Passes
  - Apps_Possessionloss
  - Apps_Saves
  - Apps_Shots
  - Apps_Tackles
  - CaughtOffside_Offsides
  - Corner_Assists
  - Cross_Assists
  - CrossesBlocked_Blocks
  - Dispossessed_Possessionloss
  - DribbledPast_Tackles
  - Fouled_Fouls
  - Fouls_Fouls
  - Freekick_Assists
  - InAccLB_Passes
  - InAccSP_Passes
  - Long_Keypasses
  - Lost_Aerial
  - Mins_Aerial
  - Other_Assists
  - OutOfBox_Goals
  - OutOfBox_Saves
  - OutOfBox_Shots
  - PassesBlocked_Blocks
  - PenaltyArea_Goals
  - PenaltyArea_Saves
  - PenaltyArea_Shots
  - Rating_Aerial
  - Red_Cards
  - Short_Keypasses
  - ShotsBlocked_Blocks
  - SixYardBox_Goals
  - SixYardBox_Saves
  - SixYardBox_Shots
  - Successful_Dribbles
  - Throughball_Assists
  - Throwin_Assists
  - TotalAttemptedTackles_Tackles
  - TotalDribbles_Dribbles
  - TotalTackles_Tackles
  - Total_Aerial
  - Total_Assists
  - Total_Clearances
  - Total_Goals
  - Total_Interception
  - Total_Keypasses
  - Total_Passes
  - Total_Saves
  - Total_Shots
  - UnsuccessfulTouches_Possessionloss
  - Unsuccessful_Dribbles
  - Won_Aerial
  - Yellow_Cards
  - age
  - days
  - height_in_cm
  - last_values
  - club_name_Arsenal FC
  - club_name_Aston Villa
  - club_name_Birmingham City
  - club_name_Blackburn Rovers
  - club_name_Blackpool FC
  - club_name_Bolton Wanderers
  - club_name_Brentford FC
  - club_name_Brighton & Hove Albion
  - club_name_Burnley FC
  - club_name_Cardiff City
  - club_name_Chelsea FC
  - club_name_Crystal Palace
  - club_name_Everton FC
  - club_name_Fulham FC
  - club_name_Huddersfield Town
  - club_name_Hull City
  - club_name_Leeds United
  - club_name_Leicester City
  - club_name_Liverpool FC
  - club_name_Manchester City
  - club_name_Middlesbrough FC
  - club_name_Newcastle United
  - club_name_Norwich City
  - club_name_Queens Park Rangers
  - club_name_Reading FC
  - club_name_Sheffield United
  - club_name_Southampton FC
  - club_name_Stoke City
  - club_name_Sunderland AFC
  - club_name_Swansea City
  - club_name_Tottenham Hotspur
  - club_name_Watford FC
  - club_name_West Bromwich Albion
  - club_name_Wigan Athletic
  - club_name_Wolverhampton Wanderers
  - club_name_not_premier
  - field_position_attacking midfield
  - field_position_central midfield
  - field_position_centre back
  - field_position_centre forward
  - field_position_defensive midfield
  - field_position_goalkeeper
  - field_position_left back
  - field_position_left midfield
  - field_position_left winger
  - field_position_right back
  - field_position_right midfield
  - field_position_right winger
  - field_position_second striker
  - foot_both
  - foot_left
  - foot_right
  - nationality_Albania
  - nationality_Algeria
  - nationality_Angola
  - nationality_Antigua and BarbudaEngland
  - nationality_Argentina
  - nationality_ArgentinaItaly
  - nationality_ArgentinaMexico
  - nationality_Armenia
  - nationality_Australia
  - nationality_Austria
  - nationality_Belgium
  - nationality_BelgiumCote d'Ivoire
  - nationality_Benin
  - nationality_Bosnia-Herzegovina
  - nationality_Brazil
  - nationality_BrazilItaly
  - nationality_Bulgaria
  - nationality_Burundi
  - nationality_Cameroon
  - nationality_CameroonSomalia
  - nationality_Canada
  - nationality_Chile
  - nationality_ChileHaiti
  - nationality_Colombia
  - nationality_Costa Rica
  - nationality_Cote d'Ivoire
  - nationality_Croatia
  - nationality_Curacao
  - nationality_Czech Republic
  - nationality_DR Congo
  - nationality_Denmark
  - nationality_Dominican Republic
  - nationality_Ecuador
  - nationality_EcuadorSpain
  - nationality_Egypt
  - nationality_England
  - nationality_EnglandAntigua and Barbuda
  - nationality_EnglandDR Congo
  - nationality_EnglandFrance
  - nationality_EnglandIreland
  - nationality_EnglandJamaica
  - nationality_EnglandMontserrat
  - nationality_EnglandNigeria
  - nationality_EnglandSeychelles
  - nationality_EnglandSierra Leone
  - nationality_EnglandWales
  - nationality_Equatorial Guinea
  - nationality_Estonia
  - nationality_Finland
  - nationality_France
  - nationality_FranceCongo
  - nationality_FranceDR Congo
  - nationality_FranceSenegal
  - nationality_French Guiana
  - nationality_Gabon
  - nationality_GabonFrance
  - nationality_Germany
  - nationality_Ghana
  - nationality_GibraltarEngland
  - nationality_Greece
  - nationality_Grenada
  - nationality_Guadeloupe
  - nationality_Guyana
  - nationality_Honduras
  - nationality_Iceland
  - nationality_Iran
  - nationality_Ireland
  - nationality_IrelandAustralia
  - nationality_IrelandEngland
  - nationality_Israel
  - nationality_IsraelItaly
  - nationality_Italy
  - nationality_Jamaica
  - nationality_JamaicaEngland
  - nationality_Japan
  - nationality_Kenya
  - nationality_Korea, South
  - nationality_Kosovo
  - nationality_Latvia
  - nationality_Mali
  - nationality_Mauritania
  - nationality_Mexico
  - nationality_Montenegro
  - nationality_MontenegroSwitzerland
  - nationality_Morocco
  - nationality_Netherlands
  - nationality_New Zealand
  - nationality_Nigeria
  - nationality_NigeriaEngland
  - nationality_North Macedonia
  - nationality_Northern Ireland
  - nationality_Norway
  - nationality_Paraguay
  - nationality_Philippines
  - nationality_Poland
  - nationality_Portugal
  - nationality_PortugalBrazil
  - nationality_Romania
  - nationality_Russia
  - nationality_Scotland
  - nationality_ScotlandEngland
  - nationality_ScotlandNigeria
  - nationality_Senegal
  - nationality_SenegalFrance
  - nationality_Serbia
  - nationality_Sierra Leone
  - nationality_Slovakia
  - nationality_Slovenia
  - nationality_South Africa
  - nationality_Spain
  - nationality_SpainItaly
  - nationality_St. Kitts & Nevis
  - nationality_Sweden
  - nationality_Switzerland
  - nationality_The Gambia
  - nationality_Togo
  - nationality_Tunisia
  - nationality_Turkey
  - nationality_Ukraine
  - nationality_United States
  - nationality_United StatesEngland
  - nationality_United StatesNigeria
  - nationality_United StatesScotland
  - nationality_Uruguay
  - nationality_Wales
  - nationality_WalesEngland
  - nationality_WalesJamaica
  - nationality_Zambia
  - nationality_Zimbabwe
  - position_attack
  - position_defender
  - position_goalkeeper
  - position_midfield
  - year_2009
  - year_2010
  - year_2011
  - year_2012
  - year_2013
  - year_2014
  - year_2015
  - year_2016
  - year_2017
  - year_2018
  - year_2019
  - year_2020
  - year_2021