includes:
  - configs/constant_configs.yml

model:
  name: sklearn.linear_model.Lasso
  tag: uan2

# inputs go to __init__ of the model (sklearn RFC model in this case)
special_inputs:
  alpha: 0.1
  fit_intercept: true
  max_iter: 10000
  tol: 0.01



trainer:
    name: sklearn_trainer
    label_type: regression
    save: 1
    tune:
      resources_per_trial:
        cpu: 2
        gpu: 0

    metrics: mse

    grid_metric:
      name: valid_mse
      mode: min


dataset:
  input_path: processed_data/merged_df_v42

features_list:

  Loan_start_year: []
  On Loan: []
  Team_1: []
  Team_10: []
  Team_11: []
  Team_12: []
  Team_13: []
  Team_14: []
  Team_15: []
  Team_16: []
  Team_17: []
  Team_18: []
  Team_19: []
  Team_2: []
  Team_20: []
  Team_21: []
  Team_22: []
  Team_23: []
  Team_24: []
  Team_25: []
  Team_26: []
  Team_27: []
  Team_28: []
  Team_29: []
  Team_3: []
  Team_30: []
  Team_31: []
  Team_32: []
  Team_33: []
  Team_34: []
  Team_35: []
  Team_36: []
  Team_37: []
  Team_38: []
  Team_39: []
  Team_4: []
  Team_40: []
  Team_41: []
  Team_42: []
  Team_43: []
  Team_44: []
  Team_45: []
  Team_46: []
  Team_47: []
  Team_48: []
  Team_49: []
  Team_5: []
  Team_50: []
  Team_51: []
  Team_52: []
  Team_53: []
  Team_54: []
  Team_55: []
  Team_56: []
  Team_57: []
  Team_58: []
  Team_59: []
  Team_6: []
  Team_60: []
  Team_61: []
  Team_62: []
  Team_63: []
  Team_64: []
  Team_65: []
  Team_66: []
  Team_67: []
  Team_68: []
  Team_69: []
  Team_7: []
  Team_70: []
  Team_71: []
  Team_72: []
  Team_73: []
  Team_74: []
  Team_75: []
  Team_76: []
  Team_77: []
  Team_8: []
  Team_9: []
  a_w_1: []
  a_w_2: []
  a_w_3: []
  acceleration: []
  age: []
  aggression: []
  agility: []
  attacking: []
  balance: []
  ball_control: []
  base_stats: []
  bov: []
  bp_1: []
  bp_10: []
  bp_11: []
  bp_12: []
  bp_13: []
  bp_14: []
  bp_15: []
  bp_2: []
  bp_3: []
  bp_4: []
  bp_5: []
  bp_6: []
  bp_7: []
  bp_8: []
  bp_9: []
  curve: []
  d_w_1: []
  d_w_2: []
  d_w_3: []
  defe: []

  dri: []
  dribbling: []
  finishing: []
  fk_accuracy: []
  foot_1: []
  foot_2: []
  gk_diving: []
  gk_handling: []
  gk_kicking: []
  gk_positioning: []
  gk_reflexes: []
  goalkeeping: []
  growth: []
  heading_accuracy: []
  interceptions: []
  ir: []
  jumping: []
  long_passing: []
  long_shots: []
  marking: []
  mentality: []
  movement: []
  nationality_1: []
  nationality_10: []
  nationality_11: []
  nationality_12: []
  nationality_13: []
  nationality_14: []
  nationality_15: []
  nationality_16: []
  nationality_17: []
  nationality_18: []
  nationality_19: []
  nationality_2: []
  nationality_20: []
  nationality_21: []
  nationality_22: []
  nationality_23: []
  nationality_24: []
  nationality_25: []
  nationality_26: []
  nationality_27: []
  nationality_28: []
  nationality_29: []
  nationality_3: []
  nationality_30: []
  nationality_31: []
  nationality_32: []
  nationality_33: []
  nationality_34: []
  nationality_35: []
  nationality_36: []
  nationality_37: []
  nationality_38: []
  nationality_39: []
  nationality_4: []
  nationality_40: []
  nationality_41: []
  nationality_42: []
  nationality_43: []
  nationality_44: []
  nationality_45: []
  nationality_46: []
  nationality_47: []
  nationality_48: []
  nationality_49: []
  nationality_5: []
  nationality_50: []
  nationality_6: []
  nationality_7: []
  nationality_8: []
  nationality_9: []
  nationality_encoded: []
  ova: []
  pac: []
  pas: []
  penalties: []
  phy: []
  positioning: []
  pot: []
  power: []
  reactions: []
  release_clause: []
  sho: []
  short_passing: []
  shot_power: []
  skill: []
  sliding_tackle: []
  sm: []
  sprint_speed: []
  stamina: []
  standing_tackle: []
  strength: []
  total_stats: []
  vision: []
  volleys: []
  w_f: []
  wage: []
