includes:
  - configs/constant_configs.yml

model:
  name: sklearn.linear_model.LinearRegression
  tag: uan2

# inputs go to __init__ of the model (sklearn RFC model in this case)
special_inputs:
  normalize: true

  
trainer:
    name: sklearn_trainer
    save: 1
    tune:
      resources_per_trial:
        cpu: 2
        gpu: 0

    metrics: mse

    grid_metric:
      name: valid_mse
      mode: min


dataset:
  input_path: processed_data/regression_output

features_list:
  - SAT

