includes:
  - configs/constant_configs.yml


model:
  name: dynamic_net
  tag: uan


# must be same names as parameters of the actual optimizer
optim:
  lr: 0.01
  weight_decay: 0.0001


# this inputs will go to your specific model __init__
special_inputs:
  lr: 0.001


  
trainer:
    name: torch_trainer
    optim: Adam
    loss: example
    save: 1
    epochs: 100
    log_valid_every: 10
    tune:
      resources_per_trial:
        cpu: 2
        gpu: 0
    metrics: [precision, accuracy]
    grid_metric:
      name: valid_precision
      mode: max

dataset:
  input_path: processed_data/toy_dataset


features_list:
  - sepal width (cm)
#  - petal length (cm)
  - petal width (cm)
  - sepal length (cm)