includes:
  - configs/constant_configs.yml

dataset:
  input_path: processed_data/merged_df_v62


model:
  name: dense_net_regression
  tag: uan


# must be same names as parameters of the actual optimizer
optim:
  lr: 0.0001
  weight_decay: [0.001, 0.0001]

# this inputs will go to your specific model __init__
special_inputs:
#  layers_sizes: [[10, 5, 10]]
  layers_sizes: [[100, 100, 10], [100, 100, 100], [50, 200, 10]]



trainer:
  name: torch_trainer
  optim: Adam
  loss: MSELoss
  save: 1
  epochs: 100000
  log_valid_every: 10000
  tune:
    resources_per_trial:
      cpu: 8
      gpu: 0
  metrics:
    - mse

  grid_metric:
    name: valid_MSELoss
    mode: min


features_list:
#  - name
#  - id
#  - nationality_encoded
#  - Team_encoded
  - total_stats
  - base_stats
  - age
  - ova
  - pot
  - foot_1
  - foot_2
  - foot.1
  - bov
  - bp_1
  - bp_2
  - bp_3
  - bp_4
  - bp_5
  - bp_6
  - bp_7
  - bp_8
  - bp_9
  - bp_10
  - bp_11
  - bp_12
  - bp_13
  - bp_14
  - bp_15
  - growth
  - joined
  - wage
  - release_clause
  - attacking
  - crossing
  - finishing
  - heading_accuracy
  - short_passing
  - volleys
  - skill
  - dribbling
  - curve
  - fk_accuracy
  - long_passing
  - ball_control
  - movement
  - acceleration
  - sprint_speed
  - agility
  - reactions
  - balance
  - power
  - shot_power
  - jumping
  - stamina
  - strength
  - long_shots
  - mentality
  - aggression
  - interceptions
  - positioning
  - vision
  - penalties
  - defending
  - marking
  - standing_tackle
  - sliding_tackle
  - goalkeeping
  - gk_diving
  - gk_handling
  - gk_kicking
  - gk_positioning
  - gk_reflexes
  - w_f
  - sm
  - a_w_1
  - a_w_2
  - a_w_3
  - d_w_1
  - d_w_2
  - d_w_3
  - ir
  - pac
  - sho
  - pas
  - dri
  - defe
  - phy
  - nationality_1
  - nationality_2
  - nationality_3
  - nationality_4
  - nationality_5
  - nationality_6
  - nationality_7
  - nationality_8
  - nationality_9
  - nationality_10
  - nationality_11
  - nationality_12
  - nationality_13
  - nationality_14
  - nationality_15
  - nationality_16
  - nationality_17
  - nationality_18
  - nationality_19
  - nationality_20
  - nationality_21
  - nationality_22
  - nationality_23
  - nationality_24
  - nationality_25
  - nationality_26
  - nationality_27
  - nationality_28
  - nationality_29
  - nationality_30
  - nationality_31
  - nationality_32
  - nationality_33
  - nationality_34
  - nationality_35
  - nationality_36
  - nationality_37
  - nationality_38
  - nationality_39
  - nationality_40
  - nationality_41
  - nationality_42
  - nationality_43
  - nationality_44
  - nationality_45
  - nationality_46
  - nationality_47
  - nationality_48
  - nationality_49
  - nationality_50
  - nationality_51
  - nationality_52
  - nationality_53
  - nationality_54
  - nationality_55
  - nationality_56
  - nationality_57
  - nationality_58
  - On Loan
  - Loan_start_year
  - Loan_end_year
  - Team_1
  - Team_2
  - Team_3
  - Team_4
  - Team_5
  - Team_6
  - Team_7
  - Team_8
  - Team_9
  - Team_10
  - Team_11
  - Team_12
  - Team_13
  - Team_14
  - Team_15
  - Team_16
  - Team_17
  - Team_18
  - Team_19
  - Team_20
  - Team_21
  - Team_22
  - Team_23
  - Team_24
  - Team_25
  - Team_26
  - Team_27
  - Team_28
  - Team_29
  - Team_30
  - Team_31
  - Team_32
  - Team_33
  - Team_34
  - Team_35
  - Team_36
  - Team_37
  - Team_38
  - Team_39
  - Team_40
  - Team_41
  - Team_42
  - Team_43
  - Team_44
  - Team_45
  - Team_46
  - Team_47
  - Team_48
  - Team_49
  - Team_50
  - Team_51
  - Team_52
  - Team_53
  - Team_54
  - Team_55
  - Team_56
  - Team_57
  - Team_58
  - Team_59
  - Team_60
  - Team_61
  - Team_62
  - Team_63
  - Team_64
  - Team_65
  - Team_66
  - Team_67
  - Team_68
  - Team_69
  - Team_70
  - Team_71
  - Team_72
  - Team_73
  - Team_74
  - Team_75
  - Team_76
  - Team_77
  - Team_78
  - Team_79
  - Team_80
  - Team_81
  - Team_82
  - Team_83
  - Team_84
  - Team_85
  - Team_86
  - Team_87
  - Team_88
  - Team_89
  - Team_90
  - Team_91
  - Team_92
  - Team_93
  - Team_94
  - Team_95
  - Team_96
  - Team_97
  - Team_98
  - Team_99
  - Team_100
  - Team_101
  - Team_102
  - Team_103
  - Team_104
  - Team_105
  - Team_106
  - Team_107
  - Team_108
  - Team_109
  - Team_110
  - Team_111
  - Team_112
  - Team_113
  - Team_114
  - Team_115
  - Team_116
  - Team_117
  - Team_118
  - Team_119
  - Team_120

