includes:
  - configs/constant_configs.yml

model:
  name: sklearn.svm.LinearSVC
  tag: uan2

# inputs go to __init__ of the model (sklearn RFC model in this case)
#special_inputs:



trainer:
    name: sklearn_trainer
    label_type: regression
    save: 1
    tune:
      resources_per_trial:
        cpu: 2
        gpu: 0

    metrics: mse

    grid_metric:
      name: valid_mse
      mode: min


dataset:
  input_path: processed_data/winequality-red

#features_list:


