includes:
  - configs/constant_configs.yml



model:
  name: dense_net
  tag: uan


# must be same names as parameters of the actual optimizer
optim:
  lr: 0.01
  weight_decay: 0.00001

evaluate_test: 1 # use best model version on test


# this inputs will go to your specific model __init__
#special_inputs:



trainer:
    name: torch_trainer
    tag: 'uan'
    save: 1
    epochs: 100
    log_valid_every: 10
    tune:
      resources_per_trial:
        cpu: 2
        gpu: 0
    metrics:
      - accuracy



dataset:
  input_path: processed_data/toy_dataset_output.csv
  type: csv


features_list:
  - sepal width (cm)
  - petal length (cm)
  - petal width (cm)
  - sepal length (cm)

