includes:
  - configs/constant_configs.yml


dataset:
  input_path: processed_data/tf_ws_merged_11012022_dups_removed2
  label_type: regression


model:
  name: xgboost.XGBRegressor
  tag: uan3

# inputs go to __init__ of the model (sklearn xgboost model in this case)
#special_inputs:
#  booster: dart
#  n_estimators: 110
#  max_depth: 32
#  gamma: 0.1
#  num_parallel_tree: 6
#  learning_rate: 0.1
#  subsample: 0.8
#  colsample_bytree: 0.8

special_inputs:
  booster: dart
  n_estimators: 20
  max_depth: 2
  gamma: .01
  num_parallel_tree: 16
  learning_rate: 0.2
  subsample: 0.1
  colsample_bytree: 0.4


trainer:
  name: sklearn_trainer
  save: 1
  tune:
    resources_per_trial:
      cpu: 1
      gpu: 0
    max_concurrent_trials: 54

  checkpoint_metric:
    name: valid_mse
    mode: min

metrics: [mse]

features_list:
#  - player_name
#  - playerid
  - AccLB_Passes
  - AccSP_Passes
  - CaughtOffside_Offsides
  - Corner_Assists
  - Cross_Assists
  - CrossesBlocked_Blocks
  - Dispossessed_Possessionloss
  - DribbledPast_Tackles
  - Fouled_Fouls
  - Fouls_Fouls
  - Freekick_Assists
  - InAccLB_Passes
  - InAccSP_Passes
  - Long_Keypasses
  - Lost_Aerial
  - Other_Assists
  - OutOfBox_Goals
  - OutOfBox_Shots
  - PassesBlocked_Blocks
  - PenaltyArea_Goals
  - PenaltyArea_Shots
  - Red_Cards
  - Short_Keypasses
  - ShotsBlocked_Blocks
  - SixYardBox_Goals
  - SixYardBox_Shots
  - Successful_Dribbles
  - Throughball_Assists
  - Throwin_Assists
  - TotalAttemptedTackles_Tackles
  - TotalDribbles_Dribbles
  - TotalTackles_Tackles
  - Total_Aerial
  - Total_Assists
  - Total_Clearances
  - Total_Goals
  - Total_Interception
  - Total_Keypasses
  - Total_Passes
  - Total_Shots
  - UnsuccessfulTouches_Possessionloss
  - Unsuccessful_Dribbles
  - Won_Aerial
  - Yellow_Cards
  - appearance
  - minutes
  - rating
  - season_end
  - season_start
  - joined_1
  - joined_10
  - joined_11
  - joined_12
  - joined_13
  - joined_14
  - joined_15
  - joined_16
  - joined_17
  - joined_18
  - joined_19
  - joined_2
  - joined_20
  - joined_21
  - joined_22
  - joined_23
  - joined_24
  - joined_25
  - joined_26
  - joined_27
  - joined_3
  - joined_4
  - joined_5
  - joined_6
  - joined_7
  - joined_8
  - joined_9
  - position_1
  - position_10
  - position_11
  - position_12
  - position_13
  - position_14
  - position_15
  - position_16
  - position_17
  - position_18
  - position_19
  - position_2
  - position_20
  - position_3
  - position_4
  - position_5
  - position_6
  - position_7
  - position_8
  - position_9

