includes:
  - configs/constant_configs.yml



model:
  name: rfc
  tag: uan

# inputs go to __init__ of the model (sklearn RFC model in this case)
special_inputs:
  n_estimators: 10
  max_depth: 2

  
trainer:
    name: sklearn_trainer
    tag: 'uan'
    resources_per_trial:
      cpu: 2
      gpu: 0
    save:
      - best
      - all

dataset:
  input_path: processed_data/toy_dataset_output.csv
  type: csv


