includes:
  - configs/constant_configs.yml


dataset:
  input_path: processed_data/iris
  name: csv_dataset
  label_type: classification

  data_loaders:

    train:
      batch_size: 4
      shuffle: true
      num_workers: 4
      multiprocessing_context: spawn
      pin_memory: true

    valid:
      batch_size: 4
      shuffle: false
      num_workers: 4
      multiprocessing_context: spawn
      pin_memory: true

    test:
      batch_size: 4
      shuffle: false
      num_workers: 4
      multiprocessing_context: spawn
      pin_memory: true


model:
  name: dense_net
  tag: uan


# must be same names as parameters of the actual optimizer
optim:
  lr: 0.01
  weight_decay: 0.00001


# this inputs will go to your specific model __init__
special_inputs:
  n_outputs: 1
  input_dim: 4

trainer:
  name: torch_trainer3
  optim: Adam
  loss: NLLLoss
  save: 1
  epochs: 2
  log_valid_every: 1
  tune:
    resources_per_trial:
      cpu: 2
      gpu: 0
  metrics:
    - accuracy
    - precision

  grid_metric:
    name: valid_precision
    mode: max


features_list:
  - sepal width (cm)
  - petal length (cm)
  - petal width (cm)
  - sepal length (cm)

