includes:
  - configs/constant_configs.yml


dataset:
  input_path: processed_data/toy_dataset
  name: csv_dataset


model:
  name: dense_net
  tag: uan


# must be same names as parameters of the actual optimizer
optim:
  lr: 0.01
  weight_decay: 0.00001


# this inputs will go to your specific model __init__
#special_inputs:



trainer:
  name: torch_trainer
  optim: Adam
  loss: NLLLoss
  save: 1
  epochs: 10
  log_valid_every: 10
  tune:
    resources_per_trial:
      cpu: 2
      gpu: 0
  metrics:
    - accuracy
    - precision

  grid_metric:
    name: valid_precision
    mode: max


features_list:
#  - sepal width (cm)
  - petal length (cm)
  - petal width (cm)
  - sepal length (cm)

