includes:
  - configs/constant_configs.yml


dataset:
  input_path: processed_data/tf_ws_merged_11012022_dups_removed2
  label_type: regression

  data_loaders:

    train:
      batch_size: 16
      shuffle: true
      num_workers: 4
      multiprocessing_context: spawn
      pin_memory: true

    valid:
      batch_size: 8
      shuffle: false
      num_workers: 4
      multiprocessing_context: spawn
      pin_memory: true

    test:
      batch_size: 1
      shuffle: false
      num_workers: 4
      multiprocessing_context: spawn
      pin_memory: true


model:
  name: dense_net_regression
  tag: uan


# must be same names as parameters of the actual optimizer
optim:
  lr: 0.0001
  weight_decay: 0.001

# this inputs will go to your specific model __init__
special_inputs:
  layers_sizes: [[30, 10, 30, 10]]
#  layers_sizes: [[100], [50, 50]]
  input_dim: 96
  n_outputs: 1


trainer:
  name: torch_trainer
  optim: Adam
  loss: exp_loss
  save: 1
  epochs: 100
  log_valid_every: 5
  tune:
    resources_per_trial:
      cpu: 8
      gpu: 0

  checkpoint_metric:
    name: valid_exp_loss
    mode: min

metrics: [mse]


features_list:
#  - player_name
#  - playerid
  - AccLB_Passes
  - AccSP_Passes
  - CaughtOffside_Offsides
  - Corner_Assists
  - Cross_Assists
  - CrossesBlocked_Blocks
  - Dispossessed_Possessionloss
  - DribbledPast_Tackles
  - Fouled_Fouls
  - Fouls_Fouls
  - Freekick_Assists
  - InAccLB_Passes
  - InAccSP_Passes
  - Long_Keypasses
  - Lost_Aerial
  - Other_Assists
  - OutOfBox_Goals
  - OutOfBox_Saves
  - OutOfBox_Shots
  - PassesBlocked_Blocks
  - PenaltyArea_Goals
  - PenaltyArea_Saves
  - PenaltyArea_Shots
  - Red_Cards
  - Short_Keypasses
  - ShotsBlocked_Blocks
  - SixYardBox_Goals
  - SixYardBox_Saves
  - SixYardBox_Shots
  - Successful_Dribbles
  - Throughball_Assists
  - Throwin_Assists
  - TotalAttemptedTackles_Tackles
  - TotalDribbles_Dribbles
  - TotalTackles_Tackles
  - Total_Aerial
  - Total_Assists
  - Total_Clearances
  - Total_Goals
  - Total_Interception
  - Total_Keypasses
  - Total_Passes
  - Total_Saves
  - Total_Shots
  - UnsuccessfulTouches_Possessionloss
  - Unsuccessful_Dribbles
  - Won_Aerial
  - Yellow_Cards
  - appearance
  - minutes
  - rating
  - season_end
  - season_start
  - joined_1
  - joined_10
  - joined_11
  - joined_12
  - joined_13
  - joined_14
  - joined_15
  - joined_16
  - joined_17
  - joined_18
  - joined_19
  - joined_2
  - joined_20
  - joined_21
  - joined_22
  - joined_23
  - joined_24
  - joined_25
  - joined_26
  - joined_27
  - joined_3
  - joined_4
  - joined_5
  - joined_6
  - joined_7
  - joined_8
  - joined_9
  - position_1
  - position_10
  - position_11
  - position_12
  - position_13
  - position_14
  - position_15
  - position_16
  - position_17
  - position_18
  - position_19
  - position_2
  - position_20
  - position_3
  - position_4
  - position_5
  - position_6
  - position_7
  - position_8
  - position_9

