includes:
  - configs/constant_configs.yml


dataset:
  input_path: processed_data/player_valuation2_no_first_year
  label_type: regression


model:
  name: sklearn.linear_model.LinearRegression
  tag: no_first_year_lr

# inputs go to __init__ of the model (sklearn xgboost model in this case)
special_inputs:
  positive: true

trainer:
  name: sklearn_trainer
  save: 1
  tune:
    resources_per_trial:
      cpu: 1
      gpu: 0
    max_concurrent_trials: 54

  checkpoint_metric:
    name: valid_mse
    mode: min

metrics: [mse]



features_list:
#  - club_id
  - last_values
#  - playerid
  - AccLB_Passes
  - AccSP_Passes
  - Apps_Aerial
  - Apps_Assists
  - Apps_Blocks
  - Apps_Cards
  - Apps_Clearances
  - Apps_Dribbles
  - Apps_Fouls
  - Apps_Goals
  - Apps_Interception
  - Apps_Keypasses
  - Apps_Offsides
  - Apps_Passes
  - Apps_Possessionloss
  - Apps_Saves
  - Apps_Shots
  - Apps_Tackles
  - CaughtOffside_Offsides
  - Corner_Assists
  - Cross_Assists
  - CrossesBlocked_Blocks
  - Dispossessed_Possessionloss
  - DribbledPast_Tackles
  - Fouled_Fouls
  - Fouls_Fouls
  - Freekick_Assists
  - InAccLB_Passes
  - InAccSP_Passes
  - Long_Keypasses
  - Lost_Aerial
  - Mins_Aerial
  - Other_Assists
  - OutOfBox_Goals
  - OutOfBox_Saves
  - OutOfBox_Shots
  - PassesBlocked_Blocks
  - PenaltyArea_Goals
  - PenaltyArea_Saves
  - PenaltyArea_Shots
  - Rating_Aerial
  - Red_Cards
  - Short_Keypasses
  - ShotsBlocked_Blocks
  - SixYardBox_Goals
  - SixYardBox_Saves
  - SixYardBox_Shots
  - Successful_Dribbles
  - Throughball_Assists
  - Throwin_Assists
  - TotalAttemptedTackles_Tackles
  - TotalDribbles_Dribbles
  - TotalTackles_Tackles
  - Total_Aerial
  - Total_Assists
  - Total_Clearances
  - Total_Goals
  - Total_Interception
  - Total_Keypasses
  - Total_Passes
  - Total_Saves
  - Total_Shots
  - UnsuccessfulTouches_Possessionloss
  - Unsuccessful_Dribbles
  - Won_Aerial
  - Yellow_Cards
  - _divided_AccLB_Passes
  - _divided_AccSP_Passes
  - _divided_Apps_Assists
  - _divided_Apps_Passes
  - _divided_CaughtOffside_Offsides
  - _divided_Corner_Assists
  - _divided_Cross_Assists
  - _divided_CrossesBlocked_Blocks
  - _divided_Dispossessed_Possessionloss
  - _divided_DribbledPast_Tackles
  - _divided_Fouled_Fouls
  - _divided_Fouls_Fouls
  - _divided_Freekick_Assists
  - _divided_InAccLB_Passes
  - _divided_InAccSP_Passes
  - _divided_Long_Keypasses
  - _divided_Lost_Aerial
  - _divided_Other_Assists
  - _divided_OutOfBox_Goals
  - _divided_OutOfBox_Saves
  - _divided_OutOfBox_Shots
  - _divided_PassesBlocked_Blocks
  - _divided_PenaltyArea_Goals
  - _divided_PenaltyArea_Saves
  - _divided_PenaltyArea_Shots
  - _divided_Rating_Aerial
  - _divided_Red_Cards
  - _divided_Short_Keypasses
  - _divided_ShotsBlocked_Blocks
  - _divided_SixYardBox_Goals
  - _divided_SixYardBox_Saves
  - _divided_SixYardBox_Shots
  - _divided_Successful_Dribbles
  - _divided_Throughball_Assists
  - _divided_Throwin_Assists
  - _divided_TotalAttemptedTackles_Tackles
  - _divided_TotalDribbles_Dribbles
  - _divided_TotalTackles_Tackles
  - _divided_Total_Aerial
  - _divided_Total_Assists
  - _divided_Total_Clearances
  - _divided_Total_Goals
  - _divided_Total_Interception
  - _divided_Total_Keypasses
  - _divided_Total_Passes
  - _divided_Total_Saves
  - _divided_Total_Shots
  - _divided_UnsuccessfulTouches_Possessionloss
  - _divided_Unsuccessful_Dribbles
  - _divided_Won_Aerial
  - _divided_Yellow_Cards
  - _divided_age
  - _divided_current_age
  - _divided_height_in_cm
  - _divided_last_values
  - age
  - club_age
  - current_age
  - days
  - height_in_cm
  - overall_standing
  - year
  - club_name_Arsenal FC
  - club_name_Aston Villa
  - club_name_Birmingham City
  - club_name_Blackburn Rovers
  - club_name_Blackpool FC
  - club_name_Bolton Wanderers
  - club_name_Brentford FC
  - club_name_Brighton & Hove Albion
  - club_name_Burnley FC
  - club_name_Cardiff City
  - club_name_Chelsea FC
  - club_name_Crystal Palace
  - club_name_Everton FC
  - club_name_Fulham FC
  - club_name_Huddersfield Town
  - club_name_Hull City
  - club_name_Leeds United
  - club_name_Leicester City
  - club_name_Liverpool FC
  - club_name_Manchester City
  - club_name_Middlesbrough FC
  - club_name_Newcastle United
  - club_name_Norwich City
  - club_name_Queens Park Rangers
  - club_name_Reading FC
  - club_name_Sheffield United
  - club_name_Southampton FC
  - club_name_Stoke City
  - club_name_Sunderland AFC
  - club_name_Swansea City
  - club_name_Tottenham Hotspur
  - club_name_Watford FC
  - club_name_West Bromwich Albion
  - club_name_Wigan Athletic
  - club_name_Wolverhampton Wanderers
  - club_name_not_premier
  - field_position_attacking midfield
  - field_position_central midfield
  - field_position_centre back
  - field_position_centre forward
  - field_position_defensive midfield
  - field_position_goalkeeper
  - field_position_left back
  - field_position_left midfield
  - field_position_left winger
  - field_position_right back
  - field_position_right midfield
  - field_position_right winger
  - field_position_second striker
  - foot_both
  - foot_left
  - foot_right
  - nationality_Algeria
  - nationality_Angola
  - nationality_Argentina
  - nationality_Armenia
  - nationality_Australia
  - nationality_Austria
  - nationality_Belgium
  - nationality_Benin
  - nationality_Bosnia-Herzegovina
  - nationality_Brazil
  - nationality_BrazilItaly
  - nationality_Bulgaria
  - nationality_Burundi
  - nationality_Cameroon
  - nationality_CameroonSomalia
  - nationality_Canada
  - nationality_Chile
  - nationality_Colombia
  - nationality_Costa Rica
  - nationality_Cote d'Ivoire
  - nationality_Croatia
  - nationality_Curacao
  - nationality_Czech Republic
  - nationality_DR Congo
  - nationality_Denmark
  - nationality_Ecuador
  - nationality_Egypt
  - nationality_England
  - nationality_EnglandAntigua and Barbuda
  - nationality_EnglandDR Congo
  - nationality_EnglandIreland
  - nationality_EnglandJamaica
  - nationality_EnglandMontserrat
  - nationality_EnglandNigeria
  - nationality_EnglandSierra Leone
  - nationality_EnglandWales
  - nationality_Estonia
  - nationality_Finland
  - nationality_France
  - nationality_FranceSenegal
  - nationality_French Guiana
  - nationality_Gabon
  - nationality_Germany
  - nationality_Ghana
  - nationality_GibraltarEngland
  - nationality_Greece
  - nationality_Guyana
  - nationality_Honduras
  - nationality_Iceland
  - nationality_Iran
  - nationality_Ireland
  - nationality_IrelandEngland
  - nationality_Israel
  - nationality_IsraelItaly
  - nationality_Italy
  - nationality_Jamaica
  - nationality_Japan
  - nationality_Kenya
  - nationality_Korea, South
  - nationality_Mali
  - nationality_Mauritania
  - nationality_Mexico
  - nationality_Montenegro
  - nationality_Morocco
  - nationality_Netherlands
  - nationality_New Zealand
  - nationality_Nigeria
  - nationality_NigeriaEngland
  - nationality_Northern Ireland
  - nationality_Norway
  - nationality_Poland
  - nationality_Portugal
  - nationality_Romania
  - nationality_Russia
  - nationality_Scotland
  - nationality_ScotlandEngland
  - nationality_ScotlandNigeria
  - nationality_Senegal
  - nationality_SenegalFrance
  - nationality_Serbia
  - nationality_Sierra Leone
  - nationality_Slovakia
  - nationality_Slovenia
  - nationality_South Africa
  - nationality_Spain
  - nationality_Sweden
  - nationality_Switzerland
  - nationality_The Gambia
  - nationality_Togo
  - nationality_Tunisia
  - nationality_Turkey
  - nationality_Ukraine
  - nationality_United States
  - nationality_Uruguay
  - nationality_Wales
  - nationality_WalesEngland
  - nationality_WalesJamaica
  - nationality_Zambia
  - nationality_Zimbabwe
  - position_attack
  - position_defender
  - position_goalkeeper
  - position_midfield