includes:
  - configs/constant_configs.yml

model:
  name: rfc
  tag: uan2

# inputs go to __init__ of the model (sklearn RFC model in this case)
special_inputs:
  n_estimators: 10
  max_depth: 2

  
trainer:
    name: sklearn_trainer
    save: 1
    tune:
      resources_per_trial:
        cpu: 2
        gpu: 0

    metrics: [accuracy, precision]

    grid_metric:
      name: valid_precision
      mode: max


dataset:
  input_path: processed_data/toy_dataset_output.csv
  type: csv


features_list:
  - sepal width (cm)
  - petal length (cm)
  - petal width (cm)
  - sepal length (cm)
