includes:
  - configs/constant_configs.yml



model:
  name: dense_net_regression
  tag: uan


# must be same names as parameters of the actual optimizer
optim:
  lr: 0.01
  weight_decay: 0.00001

evaluate_test: 1 # use best model version on test


# this inputs will go to your specific model __init__
#special_inputs:



trainer:
  name: torch_trainer
  tag: uan
  optim: Adam
  loss: MSELoss
  save: 1
  epochs: 100
  log_valid_every: 10
  tune:
    resources_per_trial:
      cpu: 2
      gpu: 0
#  metrics:
#    - mse_loss

  grid_metric:
    name: mse_loss
    mode: max




dataset:
  input_path: processed_data/regression_output.csv


features_list:
  - SAT

